const TailwindStyles = {
  container: "bg-gray-100 min-h-screen",
  header: "bg-white py-4 px-6 flex justify-between items-center",
  logo: "text-2xl font-bold",
  userInfo: "flex items-center",
  sourceCode: "text-gray-500 mr-4",
  userAvatar: "flex items-center",
  userName: "font-medium mr-2",
  userRole: "text-gray-500",
  nav: "bg-white py-4 px-6 flex",
  nav: "bg-white py-4 px-6 flex",
  "nav ul": "flex space-x-6",
  dashboard: "grid grid-cols-3 gap-6 p-6",
  dashboardItem: "bg-white rounded-lg shadow-md p-4",
  dashboardItemHeader: "flex flex-col items-center space-y-2",
  sectionTitle: "text-lg font-medium mb-4",
  chart: "bg-white rounded-lg shadow-md p-4",
  chartItem: "space-y-4",
  chartItemHeader: "grid grid-cols-3 text-gray-500 font-medium",
  chartItemContent: "space-y-2",
  chartItemRow: "grid grid-cols-4 items-center",
  chartItemRow: "grid grid-cols-4 items-center",
  chartItemRow: "grid grid-cols-4 items-center",
  chartContent: "space-y-4",
  pieChart: "flex justify-center",
  pieChartItem: "flex items-center space-x-2",
  pieChartItemColor: "w-4 h-4 rounded-full",
};

export default TailwindStyles;
